/*
 * MainFrame.java
 * @author Fred Faber                                       
 */
public class MainFrame extends javax.swing.JFrame {           
     
    private Polynomial poly = new Polynomial();
    
    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        updateView();  //redessiner
    }
    
    /**
     * Affiche le polynôme avec son équation dans le panneau 
     */
    private void updateView()                                       
    {                                      
        drawPanel.setPoly(poly);
        poly.setAntialiased(antialiasCheckBox.isSelected());
        poly.setLimits(Double.valueOf(xminTextField.getText()),
                       Double.valueOf(xmaxTextField.getText()));
        drawPanel.repaint();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        coeffTextField = new javax.swing.JTextField();
        newButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        xminTextField = new javax.swing.JTextField();
        xmaxTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        drawPanel = new DrawPanel();
        derivateButton = new javax.swing.JButton();
        antialiasCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Polynomial Plotter");

        addButton.setText("Add coefficient (least significant first)");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        coeffTextField.setText("0");
        coeffTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coeffTextFieldActionPerformed(evt);
            }
        });

        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("xmin :");

        jLabel4.setText("xmax :");

        xminTextField.setText("-5.0");
        xminTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xminTextFieldActionPerformed(evt);
            }
        });

        xmaxTextField.setText("5.0");
        xmaxTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xmaxTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Coeff.:");

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        derivateButton.setText("Derivate");
        derivateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derivateButtonActionPerformed(evt);
            }
        });

        antialiasCheckBox.setSelected(true);
        antialiasCheckBox.setText("antialias");
        antialiasCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                antialiasCheckBoxStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xminTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(coeffTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(xmaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(derivateButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(antialiasCheckBox, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(coeffTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(antialiasCheckBox))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(xmaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newButton)
                    .addComponent(xminTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(derivateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        //ajouter un coeffcient (terme) au polynôme et redessiner le graphique
        poly.add(Double.valueOf(coeffTextField.getText()));            
        coeffTextField.setText("");     
        updateView();   //redessiner
    }//GEN-LAST:event_addButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        poly = new Polynomial();         
        updateView();   //redessiner
    }//GEN-LAST:event_newButtonActionPerformed

    private void coeffTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coeffTextFieldActionPerformed
        addButton.doClick();           
    }//GEN-LAST:event_coeffTextFieldActionPerformed

    private void xminTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xminTextFieldActionPerformed
         updateView();  //redessiner                                                  
    }//GEN-LAST:event_xminTextFieldActionPerformed

    private void xmaxTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xmaxTextFieldActionPerformed
         updateView();  //redessiner 
    }//GEN-LAST:event_xmaxTextFieldActionPerformed

    private void derivateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derivateButtonActionPerformed
        MainFrame newFrame = new MainFrame(); //créer une nouvelle fiche
        newFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        //calculer la dérivée et l'attribuer à la nouvelle fiche
        newFrame.poly = poly.derivatedPolynomial();
        newFrame.drawPanel.setPoly(newFrame.poly);
        //positionner et afficher la nouvelle fiche
        newFrame.setLocation(this.getX()+30, this.getY()+30);
        newFrame.setVisible(true);
        newFrame.updateView();
    }//GEN-LAST:event_derivateButtonActionPerformed

    private void antialiasCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_antialiasCheckBoxStateChanged
        updateView();
    }//GEN-LAST:event_antialiasCheckBoxStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JCheckBox antialiasCheckBox;
    private javax.swing.JTextField coeffTextField;
    private javax.swing.JButton derivateButton;
    private DrawPanel drawPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton newButton;
    private javax.swing.JTextField xmaxTextField;
    private javax.swing.JTextField xminTextField;
    // End of variables declaration//GEN-END:variables
}