
/*
 * Mainform.java
 * Created on Jan 19, 2011, 9:36:05 PM
 * @author robertfisch
 */
public class CisternView extends javax.swing.JFrame {

    private Cistern cistern;

    public void updateView()
    {       
       currentVolumeLabel.setText( (int)(cistern.getCurrentVolume()*1000) / 1000.0 +" litres");
       percentageLabel.   setText( (int)(cistern.getPercentage  ()*1000) / 1000.0 + " %");
       maximumVolumeLabel.setText( (int)(cistern.getMaximumVolume()*1000) / 1000.0 + " litres");
       //percentageProgressBar : maximum=100 ; minimum=0
       percentageProgressBar.setValue((int)(cistern.getPercentage())); 
       //percentageProgressBar.setStringPainted(true);
    } 

    /** default constructor */
    public CisternView() {
        initComponents();
        // initialiser les dimensions. 
        cistern = new Cistern(1,2);
        updateView();       
    }

    /** new constructor */
    public CisternView(double pRadius, double pHeight) {
        initComponents();
        // initialiser les dimensions. 
        cistern = new Cistern(pRadius,pHeight);
        updateView();       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volumeTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        drainButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        percentageLabel = new javax.swing.JLabel();
        currentVolumeLabel = new javax.swing.JLabel();
        percentageProgressBar = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        maximumVolumeLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cistern");

        volumeTextField.setText("0");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        drainButton.setText("Drain");
        drainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drainButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("litres");

        jLabel2.setText("Current Volume :");

        percentageLabel.setText("0%");

        currentVolumeLabel.setText("0 litres");

        percentageProgressBar.setOrientation(1);
        percentageProgressBar.setToolTipText("");
        percentageProgressBar.setValue(50);
        percentageProgressBar.setFocusable(false);
        percentageProgressBar.setRequestFocusEnabled(false);

        jLabel3.setText("Maximum Volume :");

        maximumVolumeLabel.setText("0 litres");

        jLabel5.setText("Current Rate :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(volumeTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(drainButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(percentageLabel)
                            .addComponent(currentVolumeLabel)
                            .addComponent(maximumVolumeLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(percentageProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(drainButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(maximumVolumeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(currentVolumeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(percentageLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(percentageProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addButtonActionPerformed
    {//GEN-HEADEREND:event_addButtonActionPerformed
        double quantity = Double.valueOf(volumeTextField.getText());
        cistern.add(quantity);
        updateView();
    }//GEN-LAST:event_addButtonActionPerformed

    private void drainButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_drainButtonActionPerformed
    {//GEN-HEADEREND:event_drainButtonActionPerformed
        double quantity = Double.valueOf(volumeTextField.getText());
        cistern.drain(quantity);
        updateView();
    }//GEN-LAST:event_drainButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CisternView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel currentVolumeLabel;
    private javax.swing.JButton drainButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel maximumVolumeLabel;
    private javax.swing.JLabel percentageLabel;
    private javax.swing.JProgressBar percentageProgressBar;
    private javax.swing.JTextField volumeTextField;
    // End of variables declaration//GEN-END:variables

}
