
import java.awt.Color;
import java.awt.Graphics;

/*
 * DrawPanel.java
 *
 * Created on Apr 18, 2012, 1:56:42 PM
 * @author georges
 */
public class DrawPanel extends javax.swing.JPanel {
    
    private String text = "Hello world";

    public void setText(String text) {
        this.text = text;
        //repaint();    //ici ou dans MainFrame après l'appel de setText
    }
    
    /** Creates new form DrawPanel */
    public DrawPanel() {
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g)
    {
        // Colorier l'arrière fond du panneau en jaune
        g.setColor(Color.YELLOW);
        int w = getWidth();
        int h = getHeight();
        g.fillRect(0, 0, w, h);
        // Tracer quatre ovales de couleur non préféfinie
        g.setColor(new Color(150, 200, 200));
        g.fillOval(0, 0, w/2, h/2);
        g.fillOval(0, h/2, w/2, h/2);
        g.fillOval(w/2, 0, w/2, h/2);
        g.fillOval(w/2, h/2, w/2, h/2);
        // Dessiner deux diagonales rouges
        g.setColor(Color.RED);
        g.drawLine(0, 0, w, h);
        g.drawLine(0, h, w, 0);
        // Dessiner un rectangle relient les centres des ovales
        g.drawRect(w/4, h/4, w/2, h/2);
        // Dessiner un texte au milieu
        g.setColor(Color.BLACK);
        g.drawString(text, w/2, h/2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
