package gui;


import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import javax.swing.Timer;
import model.Game;

/**
 *
 * @author robertfisch, Fred Faber
 */
public class MainFrame extends javax.swing.JFrame {

    private Game game;
    private Timer timer;

    public MainFrame() {
        initComponents();

        timer = new Timer(20, stepButton.getActionListeners()[0]);
        stepButton.setVisible(false);
        startButton.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drawPanel = new DrawPanel();
        stepButton = new javax.swing.JButton();
        livesLabel = new javax.swing.JLabel();
        pointsLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        drawPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                drawPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                drawPanelMouseReleased(evt);
            }
        });

        stepButton.setText("Step");
        stepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepButtonActionPerformed(evt);
            }
        });

        livesLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        livesLabel.setForeground(new java.awt.Color(255, 255, 153));
        livesLabel.setText("Lives = ?");

        pointsLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pointsLabel.setForeground(new java.awt.Color(255, 255, 153));
        pointsLabel.setText("Points = ?");

        startButton.setBackground(new java.awt.Color(51, 102, 255));
        startButton.setFont(new java.awt.Font("Lucida Grande", 0, 130)); // NOI18N
        startButton.setForeground(new java.awt.Color(0, 0, 204));
        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drawPanelLayout.createSequentialGroup()
                .addGroup(drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(drawPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(livesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 676, Short.MAX_VALUE)
                        .addComponent(pointsLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drawPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(stepButton)))
                .addContainerGap())
            .addGroup(drawPanelLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drawPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(livesLabel)
                    .addComponent(pointsLabel))
                .addGap(139, 139, 139)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(stepButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepButtonActionPerformed
        game.move(drawPanel.getWidth(), drawPanel.getHeight());
        livesLabel.setText("Lives = " + game.getLives());
        pointsLabel.setText("Points = " + game.getPoints());
        if (game.getLives() == 0) {
            timer.stop();
            drawPanel.setGame(null);
            startButton.setVisible(true);
        }
        drawPanel.repaint();
    }//GEN-LAST:event_stepButtonActionPerformed

    private void drawPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawPanelMousePressed
        if (evt.getButton() == MouseEvent.BUTTON1) {
            game.ballLeft();
        } else if (evt.getButton() == MouseEvent.BUTTON3) {
            game.ballRight();
        }
    }//GEN-LAST:event_drawPanelMousePressed

    private void drawPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawPanelMouseReleased
        game.ballStop();
    }//GEN-LAST:event_drawPanelMouseReleased

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        game = new Game(drawPanel.getWidth(), drawPanel.getHeight());
        drawPanel.setGame(game);
        startButton.setVisible(false);
        timer.start();
        this.requestFocus(); //to enable keyboard control !!
    }//GEN-LAST:event_startButtonActionPerformed

    
    //opérations du clavier
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            game.ballLeft();
        } else if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            game.ballRight();
        }
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_LEFT || evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            game.ballStop();
        }
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DrawPanel drawPanel;
    private javax.swing.JLabel livesLabel;
    private javax.swing.JLabel pointsLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stepButton;
    // End of variables declaration//GEN-END:variables
}
