
import java.awt.Color;
import java.awt.event.MouseEvent;
import javax.swing.JColorChooser;

/* 
 * MVC friendlier version
 * @author Fabfr
 */
public class MainFrame extends javax.swing.JFrame {

    private Lines      lines        = new Lines();
    private Rectangles rectangles   = new Rectangles();   
    private Line       newLine      = null;
    private Rectangle  newRectangle = null;
    
    //Color used for new lines
    private Color drawColor = Color.BLUE;
    
    /*
     * Problème général :
     * ---------------------
     * Il faut tout dupliquer: les classes pour les figures, les attributs, 
     * les réactions, l'affichage...
     * 
     * Là il doit y a voir une meilleure solution...
     * 
     */
    
    /*
     * Problème en Windows : 
     * -----------------------
     * L'événement MouseDragged ne retourne pas le bouton 
     * pressé dans evt.getButton().
     * Pour cette raison, il faut mémoriser le bouton pressé dans MousePressed
     * et utiliser cette valeur mémorisée dans MouseDragged.
     * (Sous Mac OS ce problème n'apparaît pas, mais pour être compatible avec 
     * toutes les versions Java, il vaut mieux employer cette solution.)
     */
    private int pressedButton;
    
    //Debugging: pour afficher les détails de l'événement
    private String eventString = "";

    
    
    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();        
        drawPanel.setLines(lines);       
        drawPanel.setRectangles(rectangles);
    }

    public void updateView() {
        linesList.setListData(lines.toArray());
        rectanglesList.setListData(rectangles.toArray());
        repaint();
        
        //setTitle(eventString); //debugging...
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        linesList = new javax.swing.JList();
        changeColorButton = new javax.swing.JButton();
        drawPanel = new DrawPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rectanglesList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mini-Draw");

        jScrollPane1.setViewportView(linesList);

        changeColorButton.setText("Change color");
        changeColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeColorButtonActionPerformed(evt);
            }
        });

        drawPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                drawPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                drawPanelMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drawPanelMouseClicked(evt);
            }
        });
        drawPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                drawPanelMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(rectanglesList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(changeColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeColorButton))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void drawPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawPanelMousePressed
    if (evt.getButton() == MouseEvent.BUTTON1) {
        newLine = new Line(evt.getPoint(), evt.getPoint(), drawColor);
        lines.add(newLine);
    }
    if (evt.getButton() == MouseEvent.BUTTON3) {
        newRectangle = new Rectangle(evt.getPoint(), evt.getPoint(), drawColor);
        rectangles.add(newRectangle);
    }
    pressedButton = evt.getButton();
    eventString = evt.toString(); //debugging...
    
    updateView();  
}//GEN-LAST:event_drawPanelMousePressed

private void drawPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawPanelMouseDragged
    if (pressedButton == MouseEvent.BUTTON1) {
        newLine.setTo(evt.getPoint());
    }
    if (pressedButton == MouseEvent.BUTTON3) {
        newRectangle.setTo(evt.getPoint());
    }
    eventString = evt.toString(); //debugging...   
    updateView();
}//GEN-LAST:event_drawPanelMouseDragged

private void drawPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawPanelMouseReleased
    if (pressedButton == MouseEvent.BUTTON1) {
        newLine.setTo(evt.getPoint());
    }
    if (pressedButton == MouseEvent.BUTTON3) {
        newRectangle.setTo(evt.getPoint());
    }
    eventString = evt.toString(); //debugging...   
    updateView();
}//GEN-LAST:event_drawPanelMouseReleased

    private void drawPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawPanelMouseClicked
      if (evt.getClickCount()==2) {
          lines.clear();
          rectangles.clear();
      }
      updateView();
    }//GEN-LAST:event_drawPanelMouseClicked

    private void changeColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeColorButtonActionPerformed
       drawColor = JColorChooser.showDialog(this,"Choix d'une couleur", drawColor);
    }//GEN-LAST:event_changeColorButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeColorButton;
    private DrawPanel drawPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList linesList;
    private javax.swing.JList rectanglesList;
    // End of variables declaration//GEN-END:variables
}
