
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author fred faber
 */
public class DrawPanel extends javax.swing.JPanel {

    private Grid grid = null;

    public void setGrid(Grid grid) {
        this.grid = grid;
    }
    
    /**
     * Creates new form DrawPanel
     */
    public DrawPanel() {
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        //redessiner le fond en blanc
        g.setColor(Color.WHITE);
        g.fillRect(0,0,getWidth(), getHeight());
        //dessiner la grille si déjà définie
        if (grid != null)
            grid.draw(g,getWidth(), getHeight());
        System.out.println("bla");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
