/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Sep 12, 2011, 5:04:33 PM
 */

/**
 *
 * @author fred, modified georges
 */
public class MainFrame extends javax.swing.JFrame {

    private Calculator calc = null;
    private boolean firstEntry;
    private String operator;
    

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        //view layer initializes model layer
        clearAll();
    }
    
    public void clearAll()
    {
        calc = new Calculator(0.0);
        firstEntry=true;
        operator="";
        currentValueTextField.setText("0");
    }
    
    //méthode centrale qui est appelée après chaque modification dans 'calc'
    public void updateView() {
        if(firstEntry)
        {
            calc.setCurrentValue(Double.valueOf(currentValueTextField.getText()));
            firstEntry=false;
        } 
        currentValueTextField.selectAll();   //pour pouvoir entrer la prochaine valeur
        currentValueTextField.requestFocus();//retour automatique dans le champ        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentValueTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        subtractButton = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        sqrButton = new javax.swing.JButton();
        sqrtButton = new javax.swing.JButton();
        roundButton = new javax.swing.JButton();
        sinButton = new javax.swing.JButton();
        cosButton = new javax.swing.JButton();
        tanButton = new javax.swing.JButton();
        factorialButton = new javax.swing.JButton();
        equalButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        allClearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator (RPN)");

        currentValueTextField.setText("0");
        currentValueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentValueTextFieldActionPerformed(evt);
            }
        });

        addButton.setText("+");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        subtractButton.setText("-");
        subtractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractButtonActionPerformed(evt);
            }
        });

        multiplyButton.setText("*");
        multiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyButtonActionPerformed(evt);
            }
        });

        divideButton.setText("/");
        divideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonActionPerformed(evt);
            }
        });

        sqrButton.setText("sqr");
        sqrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrButtonActionPerformed(evt);
            }
        });

        sqrtButton.setText("sqrt");
        sqrtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtButtonActionPerformed(evt);
            }
        });

        roundButton.setText("round");
        roundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButtonActionPerformed(evt);
            }
        });

        sinButton.setText("sin");
        sinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinButtonActionPerformed(evt);
            }
        });

        cosButton.setText("cos");
        cosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosButtonActionPerformed(evt);
            }
        });

        tanButton.setText("tan");
        tanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanButtonActionPerformed(evt);
            }
        });

        factorialButton.setText("n!");
        factorialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorialButtonActionPerformed(evt);
            }
        });

        equalButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        equalButton.setForeground(new java.awt.Color(204, 0, 0));
        equalButton.setText("=");
        equalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalButtonActionPerformed(evt);
            }
        });

        clearButton.setText("C");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        allClearButton.setText("AC");
        allClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentValueTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(equalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(factorialButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(subtractButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(multiplyButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(divideButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sqrButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sqrtButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(roundButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sinButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cosButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tanButton)))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(allClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(subtractButton)
                    .addComponent(multiplyButton)
                    .addComponent(divideButton)
                    .addComponent(equalButton)
                    .addComponent(clearButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sqrtButton)
                            .addComponent(roundButton)
                            .addComponent(sqrButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sinButton)
                            .addComponent(cosButton)
                            .addComponent(tanButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(allClearButton)))
                .addGap(21, 21, 21)
                .addComponent(factorialButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        updateView();
        operator="add";
    }//GEN-LAST:event_addButtonActionPerformed

    private void subtractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractButtonActionPerformed
        operator="substract";
        updateView();
    }//GEN-LAST:event_subtractButtonActionPerformed

    private void multiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyButtonActionPerformed
        operator="multiply";
        updateView();
    }//GEN-LAST:event_multiplyButtonActionPerformed

    private void divideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButtonActionPerformed
        operator="divide";
        updateView();
    }//GEN-LAST:event_divideButtonActionPerformed

    private void cosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosButtonActionPerformed
        operator="cos";
        updateView();
    }//GEN-LAST:event_cosButtonActionPerformed

    private void sqrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrButtonActionPerformed
        operator="sqr";
        updateView();
    }//GEN-LAST:event_sqrButtonActionPerformed

    private void roundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButtonActionPerformed
        operator="round";
        updateView();
    }//GEN-LAST:event_roundButtonActionPerformed

    private void sinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinButtonActionPerformed
        operator="sin";
        updateView();
    }//GEN-LAST:event_sinButtonActionPerformed

    private void tanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanButtonActionPerformed
        operator="tan";
        updateView();
    }//GEN-LAST:event_tanButtonActionPerformed

    private void factorialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorialButtonActionPerformed
        operator="factorial";
        updateView();
    }//GEN-LAST:event_factorialButtonActionPerformed

    private void sqrtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtButtonActionPerformed
        operator="sqrt";
        updateView();
    }//GEN-LAST:event_sqrtButtonActionPerformed

    private void equalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalButtonActionPerformed
        switch(operator){
            case "add": calc.add(Double.valueOf(currentValueTextField.getText()));break;
            case "substract": calc.subtract(Double.valueOf(currentValueTextField.getText()));break;
            case "multiply": calc.multiplyBy(Double.valueOf(currentValueTextField.getText()));break;
            case "divide": calc.divideBy(Double.valueOf(currentValueTextField.getText()));break;
            case "cos": calc.cos();break;
            case "sqr": calc.sqr();break;
            case "round": calc.round();break;
            case "sin": calc.sin();break;
            case "tan":calc.tan();break;
            case "factorial":calc.factorial();break;
            case "sqrt": calc.sqrt(); break;
        }
        if(calc.getErrorNote())
        {
            currentValueTextField.setText("ERROR");
            calc.setErrorNote(false);
        }
        else
        {
        currentValueTextField.setText(String.valueOf(calc.getCurrentValue()));
        }
        currentValueTextField.requestFocus();
    }//GEN-LAST:event_equalButtonActionPerformed

    private void currentValueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentValueTextFieldActionPerformed
        //Amélioration : Si on tape sur la touche Enter,
        //la méthode enterButtonActionPerformed est exécutée automatiquement.
        equalButton.doClick();
    }//GEN-LAST:event_currentValueTextFieldActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        currentValueTextField.setText("0");
        updateView();
        // TODO add your handling code here:
    }//GEN-LAST:event_clearButtonActionPerformed

    private void allClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allClearButtonActionPerformed
        clearAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_allClearButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton allClearButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton cosButton;
    private javax.swing.JTextField currentValueTextField;
    private javax.swing.JButton divideButton;
    private javax.swing.JButton equalButton;
    private javax.swing.JButton factorialButton;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton roundButton;
    private javax.swing.JButton sinButton;
    private javax.swing.JButton sqrButton;
    private javax.swing.JButton sqrtButton;
    private javax.swing.JButton subtractButton;
    private javax.swing.JButton tanButton;
    // End of variables declaration//GEN-END:variables

}
