import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/*
 * MainFrame.java
 *
 * Created 2015
 * @author Fred Faber
 */
public class MainFrame extends javax.swing.JFrame
{
    private MovingBalls balls = null;
    private Timer timer;
    private int speed = 20;
    private DrawPanel drawPanel = new DrawPanel();

    /** 
     * Creates new form MainFrame 
     */
    public MainFrame()    {
        this.setUndecorated(true);
        
//        this.setOpacity(0f);
//        initComponents();
        
        this.setExtendedState(this.MAXIMIZED_BOTH);
        
//        getContentPane().setBackground(new Color(0,255,0,0));
        setBackground(new Color(255,0,0,0));  //background transparent
        getContentPane().add(drawPanel);
        
        balls = new MovingBalls();
        drawPanel.setBalls(balls);
        
        java.awt.EventQueue.invokeLater(new Runnable()  //wait for form to have acquired his size
        {
            public void run()
            {
                startBubbles();
            }
        });
    }
    
    private double rand(double min, double max) {
        return Math.random()*(max-min)+min;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void startBubbles() {
        for(int i=0;i<10;i++)
        {
            int radius = 100;
            double x = rand ( radius, getWidth()-radius );
            double y = rand ( radius, getHeight()-radius );
            double xStep = rand ( -5, 5 );
            double yStep = rand ( -5, 5 );
            MovingBall newBall= new MovingBall (x,y,radius,xStep,yStep);            
            balls.add(newBall);
        }
        drawPanel.repaint();
        
        timer = new Timer(speed, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                balls.doStep(drawPanel.getWidth(), drawPanel.getHeight());
                drawPanel.repaint();            
            }
        });
        timer.start();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}