/*
 * Mainform.java
 *
 * Created on Jan 16, 2011, 8:53:46 PM
 * @author robert fisch, fred faber
 */
public class MainFrame extends javax.swing.JFrame {

    // créer une devinette
    private SecretNumber number = null;

    /** Creates new form Mainform */
    public MainFrame() {
        initComponents();
        // initialiser la devinette
        number = new SecretNumber(100);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        guessTextField = new javax.swing.JTextField();
        nTriesLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guess Secret Number");

        jLabel1.setText("The computer choses a random number between");

        jLabel2.setText("1 and 100. Guess it!");

        jLabel3.setText("Please enter a number and press <Enter>!");

        guessTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessTextFieldActionPerformed(evt);
            }
        });

        nTriesLabel.setText("-");

        messageLabel.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(guessTextField)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nTriesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guessTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nTriesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guessTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_guessTextFieldActionPerformed
    {//GEN-HEADEREND:event_guessTextFieldActionPerformed
        // lire le nombre de l'utilisateur
        int guessedNumber = Integer.valueOf(guessTextField.getText());

        //version 1: utilise le texte retourné par number.guess(...)
        messageLabel.setText(number.guess(guessedNumber));

        //version 2: utilise number.compareTo(...) et produit un texte alternatif
//        // si le nombre n'a pas encore été deviné
//        if (!messageLabel.getText().equals("Well done!")) {
//            // évaluer le nombre entré avec compareTo
//            int returnCode = number.compareTo(guessedNumber);
//            // afficher un texte en fonction du code de retour
//            if (returnCode == 0) {
//                messageLabel.setText("Well done!");
//            } else if (returnCode > 0) {
//                messageLabel.setText("Number too big ...");
//            } else {
//                messageLabel.setText("Number too small ...");
//            }
//        }

        // afficher le nombre de tentatives
        nTriesLabel.setText("Number of tries: " + number.getCounter());

        //Amélioration de l'ergonomie => pas besoin d'effacer l'ancien nombre entré
        guessTextField.selectAll();
        guessTextField.requestFocus();
    }//GEN-LAST:event_guessTextFieldActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField guessTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel nTriesLabel;
    // End of variables declaration//GEN-END:variables

}