
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;

/**
 * Class name: MainFrame
 *
 * @version 2019
 * @author fabfr
 */
public class MainFrame extends javax.swing.JFrame {


    private Point lastDragPosition = null;
    private Point mousePressedPosition = null;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                g = getGraphics();  //has to be called from EDT, and be executed after setVisible (see main)
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Graphics g = getGraphics();
        g.setColor(Color.black);
        g.drawLine(lastDragPosition.x, lastDragPosition.y, evt.getX(), evt.getY());
        lastDragPosition = evt.getPoint();
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        Graphics g = getGraphics();
        g.setColor(Color.red);
        g.drawLine(evt.getX(), evt.getY(), evt.getX(), evt.getY());
        g.drawOval(evt.getX() - 3, evt.getY() - 3, 6, 6);
        lastDragPosition = evt.getPoint(); //initialisation pour 'gribouillages'
        mousePressedPosition = evt.getPoint(); //initialisation pour dessin de lignes 
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        Graphics g = getGraphics();
        g.setColor(Color.blue);
        g.drawLine(evt.getX(), evt.getY(), evt.getX(), evt.getY());
        g.drawOval(evt.getX() - 3, evt.getY() - 3, 6, 6);
        g.setColor(Color.red);
        g.drawLine(
                mousePressedPosition.x, mousePressedPosition.y, evt.getX(), evt.getY());
    }//GEN-LAST:event_formMouseReleased

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        Graphics g = getGraphics();
        g.setColor(Color.green);
        g.drawLine(evt.getX(), evt.getY(), evt.getX(), evt.getY());
    }//GEN-LAST:event_formMouseMoved

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Graphics g = getGraphics();
        g.setColor(Color.yellow);
        g.drawLine(evt.getX(), evt.getY(), evt.getX(), evt.getY());
        g.fillOval(evt.getX() - 3, evt.getY() - 3, 6, 6);
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
