
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;



public class DrawPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrawPanel
     */
    private int fX = -5;
    private int fY = -5;
    private int tX = -5;
    private int tY = -5;
    private ArrayList<Lignes> alLignes = new ArrayList<>();

    public void setStart(int px, int py) {
        fX = px;
        fY = py;
    }

    public void setEnd(int px, int py) {
        tX = px;
        tY = py;
    }

    public void add(Lignes pLignes) {
        alLignes.add(pLignes);
    }
    
    public void clear() {
        alLignes.removeAll(alLignes);
    }

    public DrawPanel() {
        initComponents();
    }
    
    

    public void paintComponent(Graphics g) {
        int w = getWidth();
        int h = getHeight();

        g.setColor(Color.WHITE);
        g.fillRect(0, 0, w, h);

        if (alLignes.size() > 0) {
            for (int i = 0; i < alLignes.size(); i++) {
                g.setColor(Color.BLACK);
                g.drawLine(alLignes.get(i).getSX(), alLignes.get(i).getSY(), alLignes.get(i).getEX(), alLignes.get(i).getEY());
            }
        }

        g.setColor(Color.BLACK);
        g.drawLine(fX, fY, tX, tY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
