package gui;

import java.io.File;
import javax.swing.JOptionPane;
import model.*;

/**
 * Class name: MainFrame
 *
 * @version Feb 3, 2014
 * @author fred
 */
public class MainFrame extends javax.swing.JFrame {

    private SongList songList = new SongList();
    private Cd cd = new Cd(74.0); //init in minutes
    
    private String fileName = "songlist.txt";

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        if (new File(fileName).exists())           // version 
            songList.loadFromTextFile(fileName);   // deluxe
        updateView();
    }

    public void updateView() {
        songListView.setListData(songList.toArray());
        cdList.setListData(cd.toArray());        
        
        songListDurationLabel.setText(songList.calculateDuration() + "s");
        cdDurationLabel.setText(cd.calculateDuration() + "s");
        cdFreeCapacityLabel.setText(cd.getFreeCapacity() + "s");
        cdTotalCapacityLabel.setText(cd.getCapacity() + "s");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        songListView = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        cdList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        artistTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        durationTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        addToCDButton = new javax.swing.JButton();
        sortButton = new javax.swing.JButton();
        findLongestButton = new javax.swing.JButton();
        compileCDButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        songListDurationLabel = new javax.swing.JLabel();
        cdDurationLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cdFreeCapacityLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cdTotalCapacityLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        songListView.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                songListViewValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(songListView);

        jScrollPane2.setViewportView(cdList);

        jLabel1.setText("Song List:");

        jLabel2.setText("CD:");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel3.setText("Artist:");

        jLabel4.setText("Title:");

        jLabel5.setText("Duration (s):");

        addButton.setText("Add to list");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        addToCDButton.setText("> > >  Add selected song to CD  > > >");
        addToCDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCDButtonActionPerformed(evt);
            }
        });

        sortButton.setText("Sort");
        sortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortButtonActionPerformed(evt);
            }
        });

        findLongestButton.setText("Find and select the longest song");
        findLongestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findLongestButtonActionPerformed(evt);
            }
        });

        compileCDButton.setText("> > > Compile CD (of selected artist)  > > >");
        compileCDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compileCDButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addToCDButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(durationTextField)
                            .addComponent(titleTextField)
                            .addComponent(artistTextField)
                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(findLongestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sortButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(compileCDButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(artistTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(durationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findLongestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(addToCDButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compileCDButton))
        );

        jLabel6.setText("Duration:");

        jLabel7.setText("Duration:");

        songListDurationLabel.setText("0");

        cdDurationLabel.setText("0");

        jLabel10.setText("Free capacity:");

        cdFreeCapacityLabel.setText("0");

        jLabel12.setText("Total capacity:");

        cdTotalCapacityLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(songListDurationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(39, 39, 39)
                                        .addComponent(cdDurationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cdFreeCapacityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cdTotalCapacityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(songListDurationLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cdDurationLabel)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cdTotalCapacityLabel))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cdFreeCapacityLabel))
                        .addContainerGap())))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Song song = new Song(
                artistTextField.getText(), titleTextField.getText(), 
                Integer.valueOf(durationTextField.getText()));
        if (!songList.add(song)) {
            JOptionPane.showMessageDialog(rootPane, "The selected song is song is already in the list.");
        }
        updateView();
    }//GEN-LAST:event_addButtonActionPerformed

    private void addToCDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCDButtonActionPerformed
        if (songListView.getSelectedIndex() > -1) {
            Song song = songList.get(songListView.getSelectedIndex());
            if (!cd.add(song)) {
                JOptionPane.showMessageDialog(rootPane, "The selected song is song is already in the list.");
            }
            updateView();
        }
    }//GEN-LAST:event_addToCDButtonActionPerformed

    private void findLongestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findLongestButtonActionPerformed
        int i = songList.findIndexOfLongestSong();
        songListView.setSelectedIndex(i);
        //pas de updateView(), car alors la sélection disparaîtrait (à cause de setListData)
    }//GEN-LAST:event_findLongestButtonActionPerformed

    private void sortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortButtonActionPerformed
        songList.sort();
        updateView();
    }//GEN-LAST:event_sortButtonActionPerformed

    private void compileCDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compileCDButtonActionPerformed
        if (songListView.getSelectedIndex() > -1) {
            String artist = songList.get(songListView.getSelectedIndex()).getArtist();

            cd = songList.compileCd(artist, 74 * 60);
            updateView();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please select an artist in the list.");
        }
    }//GEN-LAST:event_compileCDButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        songList.saveToTextFile(fileName);  //version deluxe
    }//GEN-LAST:event_formWindowClosing

    private void songListViewValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_songListViewValueChanged
        //Automatically show selected song in the text fields, 
        if (songListView.getSelectedIndex() > -1) {
            Song song = songList.get(songListView.getSelectedIndex());
            titleTextField.setText(song.getTitle());
            artistTextField.setText(song.getArtist());
            durationTextField.setText(String.valueOf(song.getDuration()));
        } else { // ... or clear the fields
            titleTextField.setText("");
            artistTextField.setText("");
            durationTextField.setText("");
        }
        //pas de updateView(), car alors la sélection disparaîtrait (à cause de setListData)
    }//GEN-LAST:event_songListViewValueChanged

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addToCDButton;
    private javax.swing.JTextField artistTextField;
    private javax.swing.JLabel cdDurationLabel;
    private javax.swing.JLabel cdFreeCapacityLabel;
    private javax.swing.JList cdList;
    private javax.swing.JLabel cdTotalCapacityLabel;
    private javax.swing.JButton compileCDButton;
    private javax.swing.JTextField durationTextField;
    private javax.swing.JButton findLongestButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel songListDurationLabel;
    private javax.swing.JList songListView;
    private javax.swing.JButton sortButton;
    private javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables
}
