/*
 * MainFrame.java
 * Created on Jan 16, 2011, 8:16:27 PM
 * @author robert fisch & Fred Faber
 */
public class MainFrame extends javax.swing.JFrame {

    private Fraction fraction = null;

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        //view initialise model
        fraction = getFractionFromTextFields();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numeratorTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        denominatorTextField = new javax.swing.JTextField();
        reduceButton = new javax.swing.JButton();
        sumButton = new javax.swing.JButton();
        substractButton = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();
        divisionButton = new javax.swing.JButton();
        denominatorLabel = new javax.swing.JLabel();
        enterButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        decimalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fractions");

        numeratorTextField.setText("0");

        jLabel2.setText("-----------");

        denominatorTextField.setText("1");

        reduceButton.setText("Reduce");
        reduceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reduceButtonActionPerformed(evt);
            }
        });

        sumButton.setText("+");
        sumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumButtonActionPerformed(evt);
            }
        });

        substractButton.setText("-");
        substractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substractButtonActionPerformed(evt);
            }
        });

        multiplyButton.setText("*");
        multiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyButtonActionPerformed(evt);
            }
        });

        divisionButton.setText("/");
        divisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionButtonActionPerformed(evt);
            }
        });

        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("=");

        decimalLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numeratorTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(denominatorTextField, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(enterButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(reduceButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(substractButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sumButton))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(divisionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(multiplyButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(decimalLabel)))
                .addGap(146, 146, 146)
                .addComponent(denominatorLabel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(denominatorLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sumButton)
                                    .addComponent(multiplyButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(substractButton)
                                    .addComponent(divisionButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numeratorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(decimalLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(denominatorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(enterButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reduceButton)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //==========================================================================
    // Méthode servant à simplifier la gestion de l'interface
    //==========================================================================

    /**
     * Conversion des valeurs des champs de données et
     * retour comme fraction.
     */
    private Fraction getFractionFromTextFields()
    {
        int numerator   = Integer.valueOf(numeratorTextField.  getText());
        int denominator = Integer.valueOf(denominatorTextField.getText());
       return  new Fraction(numerator, denominator);
    }
    /**
     * Conversion des résultats de la fraction et affichage des résultats
     * dans les champs prévus.
     */
    private void updateView()
    {
        numeratorTextField.  setText(String.valueOf(fraction.getNumerator()));
        denominatorTextField.setText(String.valueOf(fraction.getDenominator()));
        decimalLabel        .setText(String.valueOf(fraction.getDecimal()));
    }

    //==========================================================================


    /**
     * simplifie la première fraction
     * @param evt
     */
    private void reduceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reduceButtonActionPerformed
        // convertir et affecter les valeurs entrées à la fraction principale
        fraction = getFractionFromTextFields();
        // faire le calcul
        fraction.reduce() ;
        // afficher le résulat
        updateView();
    }//GEN-LAST:event_reduceButtonActionPerformed


    /**
     * additionne les deux fractions
     * @param evt
     */
    private void sumButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sumButtonActionPerformed
    {//GEN-HEADEREND:event_sumButtonActionPerformed
        // convertir et affecter les valeurs entrées à une fraction temporaire
        Fraction temp = getFractionFromTextFields(); //la fraction à ajouter
        // faire le calcul 
        fraction.add( temp );
        // afficher le résulat
        updateView();
    }//GEN-LAST:event_sumButtonActionPerformed

    /**
     * multiplie les deux fractions
     * @param evt
     */
    private void multiplyButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_multiplyButtonActionPerformed
    {//GEN-HEADEREND:event_multiplyButtonActionPerformed
        // convertir et affecter les valeurs entrées à une fraction temporaire
        Fraction temp = getFractionFromTextFields(); //la fraction  par laquelle on multiplie
        // faire le calcul
        fraction.multiply( temp );
        // afficher le résulat
        updateView();
    }//GEN-LAST:event_multiplyButtonActionPerformed

    /**
     * calcule la différence des deux fractions
     * @param evt
     */
    private void substractButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_substractButtonActionPerformed
    {//GEN-HEADEREND:event_substractButtonActionPerformed
        // convertir et affecter les valeurs entrées à une fraction temporaire
        Fraction temp = getFractionFromTextFields(); //la fraction à soustraire
        // faire le calcul
        fraction.subtract( temp );
        // afficher le résulat
        updateView();
    }//GEN-LAST:event_substractButtonActionPerformed

    /**
     * divise la première fraction par la deuxième
     * @param evt
     */
    private void divisionButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_divisionButtonActionPerformed
    {//GEN-HEADEREND:event_divisionButtonActionPerformed
        // convertir et affecter les valeurs entrées à une fraction temporaire
        Fraction temp = getFractionFromTextFields(); //la fraction par laquelle on divise
        // faire le calcul
        fraction.divide( temp );
        // afficher le résulat
        updateView();
    }//GEN-LAST:event_divisionButtonActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        // convertir et affecter les valeurs entrées à la fraction principale
        fraction = getFractionFromTextFields();
        // afficher le résulat
        updateView();
    }//GEN-LAST:event_enterButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel decimalLabel;
    private javax.swing.JLabel denominatorLabel;
    private javax.swing.JTextField denominatorTextField;
    private javax.swing.JButton divisionButton;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JTextField numeratorTextField;
    private javax.swing.JButton reduceButton;
    private javax.swing.JButton substractButton;
    private javax.swing.JButton sumButton;
    // End of variables declaration//GEN-END:variables

}
