
import java.awt.Color;
import java.awt.Graphics;

/*
 * DrawPanel.java
 * @author Robert Fisch, Fred Faber
 * @version 2013-01-14
 */
public class DrawPanel extends javax.swing.JPanel {

    /**
     * une référence vers le modèle
     */
    private Checkers checkers = null;

    /**
     * Creates new form DrawPanel
     */
    public DrawPanel() {
        initComponents();
    }

    /**
     * modificateur pour la référence au modèle
     */
    public void setCheckers(Checkers pCheckers) {
        checkers = pCheckers;
    }

    /**
     * méthode dessinant le damier
     */
    @Override
    public void paintComponent(Graphics g) {
        //effacer le dessin actuel
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, getWidth(), getHeight());

        if (checkers != null) {
            checkers.draw(g, getWidth(), getHeight());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
