
import java.awt.Color;
import java.awt.Graphics;

/*
 * DrawPanel.java
 *
 * Created on Jul 6, 2012, 8:42:06 AM
 *
 * @author Georges Kugener
 */
public class DrawPanel extends javax.swing.JPanel {
    
    private Chronometer chronometer;

    public void setChronometer(Chronometer pChrono) {
        chronometer = pChrono;
    }

    /** Creates new form DrawPanel */
    public DrawPanel() {
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g)
    {
        int width = getWidth();
        int height = getHeight();
        
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, width, height);
        
        if (chronometer != null)
            chronometer.draw(g, width, height);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
