/*
 * MainFrame.java - SchoolSubjectS
 * Created on Feb 2, 2011, 10:20:03 AM
 * @author fred faber
 */
public class MainFrame extends javax.swing.JFrame {

    //List of all Schoolsubjects
    private SchoolSubjects schoolSubjects = new SchoolSubjects();
    //index of the current Schoolsubject in the list
    private int  currentSchoolSubject = -1;
    
    /** Creates new form NewJFrame */
    public MainFrame() {
        initComponents();
        updateView();
    }

    private void updateView() {
        
        //afficher la liste des branches
        //Attention: la sélection disparaît => backup & restore...
        int currentSelectionIndex = currentSchoolSubject; //backup SelectionIndex
        schoolSubjectsList.setListData(schoolSubjects.toArray());
        schoolSubjectsList.setSelectedIndex(currentSelectionIndex); //restore SelectionIndex
    
        
        if (currentSchoolSubject != -1) {
            mainPanel.setVisible(true);
            //schoolSubject <-- le sujet actuel
            SchoolSubject schoolSubject = schoolSubjects.get(currentSchoolSubject);
            
            
            // la liste des notes
            scoresList.setListData(schoolSubject.toArray());
            courseLabel.setText   (schoolSubject.getName());
            // la moyenne, le minimum et le maximum des notes
            averageLabel.setText(String.valueOf(schoolSubject.calculateRoundedAverage()));
            minLabel.setText(    String.valueOf(schoolSubject.getWorstMark()));
            maxLabel.setText(    String.valueOf(schoolSubject.getBestMark()));
        }
        else mainPanel.setVisible(false); //cacher le panneau principal si nécessaire        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        clearButton = new javax.swing.JButton();
        minLabel = new javax.swing.JLabel();
        maxLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        averageLabel = new javax.swing.JLabel();
        courseLabel = new javax.swing.JLabel();
        markTextfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        scoresList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        schoolSubjectsList = new javax.swing.JList();
        createButton = new javax.swing.JButton();
        nameTextfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        deleteSubjectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Branche GUI");

        mainPanel.setBackground(new java.awt.Color(255, 255, 204));

        clearButton.setText("Clear list");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        minLabel.setText("-");

        maxLabel.setText("-");

        addButton.setText("Add mark");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        averageLabel.setText("-");

        courseLabel.setText("-");

        markTextfield.setText("60");
        markTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markTextfieldActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(scoresList);

        jLabel2.setText("Marks");

        jLabel4.setText("Subjectname:");

        jLabel3.setText("Average:");

        jLabel5.setText("Min:");

        jLabel6.setText("Max:");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(courseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(averageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(maxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(175, 175, 175))
                                    .addComponent(minLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(markTextfield, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(courseLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(markTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addButton)
                        .addGap(32, 32, 32)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(averageLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maxLabel)))
                        .addGap(12, 12, 12)
                        .addComponent(clearButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        schoolSubjectsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                schoolSubjectsListMousePressed(evt);
            }
        });
        schoolSubjectsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                schoolSubjectsListValueChanged(evt);
            }
        });
        schoolSubjectsList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                schoolSubjectsListKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(schoolSubjectsList);

        createButton.setText("Create new subject");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        nameTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextfieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Name of new subject:");

        deleteSubjectButton.setText("Delete current subject");
        deleteSubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSubjectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTextfield)
                    .addComponent(createButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(deleteSubjectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteSubjectButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_createButtonActionPerformed
    {//GEN-HEADEREND:event_createButtonActionPerformed
        schoolSubjects.add( new SchoolSubject(nameTextfield.getText()) );
        currentSchoolSubject = schoolSubjects.size()-1;
        //montrer le panneau principal (jaune)
        mainPanel.setVisible(true);
        // mettre à jour l'interface
        updateView();
        
        // vider le champ d'entrée
        nameTextfield.selectAll();
        // positionner le cursor dans le champs d'entrée
        nameTextfield.requestFocus();
    }//GEN-LAST:event_createButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addButtonActionPerformed
    {//GEN-HEADEREND:event_addButtonActionPerformed
        //schoolSubject <-- le sujet actuel
        SchoolSubject schoolSubject = schoolSubjects.get(currentSchoolSubject);
        // mettre à jour le modèle
        schoolSubject.addMark(Integer.valueOf(markTextfield.getText()));
        
        // mettre à jour l'interface
        updateView();
        // vider le champ d'entrée
        markTextfield.selectAll();
        // positionner le cursor dans le champs d'entrée
        markTextfield.requestFocus();
    }//GEN-LAST:event_addButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clearButtonActionPerformed
    {//GEN-HEADEREND:event_clearButtonActionPerformed
        //schoolSubject <-- le sujet actuel
        SchoolSubject schoolSubject = schoolSubjects.get(currentSchoolSubject);
        schoolSubject.clear();
        // mettre à jour l'interface
        updateView();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void nameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextfieldActionPerformed
        //Amélioration de l'ergonomie: évite de devoir cliquer sur le bouton create
        //=> évite de devoir alterner entrer clavier et souris
        createButton.doClick(); //réagir à 'Enter' dans le champ create
    }//GEN-LAST:event_nameTextfieldActionPerformed

    private void schoolSubjectsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_schoolSubjectsListValueChanged
        //Cette méthode est appelée aussi lors d'un setListData -> Selection disparaît
        //==> Solution: employer MousePressed ET KeyReleased
        //(KeyPressed ne fonctionne pas, parce que l'indice sera toujours 
        //celui de l'élément sélectionné ANTERIEUREMENT )
        //currentSchoolSubject = schoolSubjectsList.getSelectedIndex();
        //updateView();
    }//GEN-LAST:event_schoolSubjectsListValueChanged

    private void schoolSubjectsListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoolSubjectsListMousePressed
        currentSchoolSubject = schoolSubjectsList.getSelectedIndex();
        updateView();
    }//GEN-LAST:event_schoolSubjectsListMousePressed

    private void schoolSubjectsListKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_schoolSubjectsListKeyReleased
        currentSchoolSubject = schoolSubjectsList.getSelectedIndex();
        updateView();
    }//GEN-LAST:event_schoolSubjectsListKeyReleased

    private void deleteSubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSubjectButtonActionPerformed
        if (currentSchoolSubject != -1) 
            schoolSubjects.remove(currentSchoolSubject);
        if (currentSchoolSubject == schoolSubjects.size())  
            currentSchoolSubject--;
        updateView();
    }//GEN-LAST:event_deleteSubjectButtonActionPerformed

    private void markTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markTextfieldActionPerformed
        //Amélioration de l'ergonomie: évite de devoir cliquer sur le bouton add
        //=> évite de devoir alterner entrer clavier et souris
        addButton.doClick();
    }//GEN-LAST:event_markTextfieldActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel averageLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel courseLabel;
    private javax.swing.JButton createButton;
    private javax.swing.JButton deleteSubjectButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField markTextfield;
    private javax.swing.JLabel maxLabel;
    private javax.swing.JLabel minLabel;
    private javax.swing.JTextField nameTextfield;
    private javax.swing.JList schoolSubjectsList;
    private javax.swing.JList scoresList;
    // End of variables declaration//GEN-END:variables

}
