
import java.awt.Color;
import java.awt.Graphics;

/*
 * DrawPanel.java
 * @author FisRo156, Fabfr(MVC)
 */
public class DrawPanel extends javax.swing.JPanel {

    private Lines lines;

    /**
     * Creates new form DrawPanel
     */
    public DrawPanel() {
        initComponents();
    }

    public void setLines(Lines pLines) {
        lines = pLines;
    }

    @Override
    public void paintComponent(Graphics g) {
        // vider la surface
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, getWidth(), getHeight());
        if (lines != null) {
            lines.draw(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
