/*
 * MainFrame.java
 *
 * Created on Sep 6, 2011, 7:41:40 PM
 *
 * @author  Michel Mercatoris & Fred Faber & Jens Getreu
 */
public class MainFrame extends javax.swing.JFrame {

    //define own components of the form
    private UniversalTime uTime;// = new UniversalTime(12,50, 1);

    /** Creates new form MainFrame */
    public MainFrame()
    {
        initComponents() ; 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        setTimeButton = new javax.swing.JButton();
        localTimeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        systemTimeButton = new javax.swing.JButton();
        minutesTextField = new javax.swing.JTextField();
        hoursTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        utcButton = new javax.swing.JButton();
        newYorkButton = new javax.swing.JButton();
        tallinnButton = new javax.swing.JButton();
        losAngelesButton = new javax.swing.JButton();
        bangkokButton = new javax.swing.JButton();
        moscowButton = new javax.swing.JButton();
        delhiButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setTimeButton.setText("Set Time");
        setTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTimeButtonActionPerformed(evt);
            }
        });

        localTimeLabel.setText("-");

        jLabel1.setText("Local Time :");

        systemTimeButton.setText("Set To System Time");
        systemTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemTimeButtonActionPerformed(evt);
            }
        });

        minutesTextField.setText("0");

        hoursTextField.setText("0");

        jLabel2.setText("hours");

        jLabel3.setText("min");

        jLabel4.setText("Foreign Time :");

        timeLabel.setText("-");

        utcButton.setText("UTC");
        utcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utcButtonActionPerformed(evt);
            }
        });

        newYorkButton.setText("New York");
        newYorkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newYorkButtonActionPerformed(evt);
            }
        });

        tallinnButton.setText("Tallinn");
        tallinnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tallinnButtonActionPerformed(evt);
            }
        });

        losAngelesButton.setText("Los Angeles");
        losAngelesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                losAngelesButtonActionPerformed(evt);
            }
        });

        bangkokButton.setText("Bangkok");
        bangkokButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkokButtonActionPerformed(evt);
            }
        });

        moscowButton.setText("Moscow");
        moscowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moscowButtonActionPerformed(evt);
            }
        });

        delhiButton.setText("Delhi");
        delhiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delhiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeLabel)
                    .addComponent(localTimeLabel))
                .addContainerGap(286, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(hoursTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(minutesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bangkokButton)
                    .addComponent(losAngelesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delhiButton)
                    .addComponent(moscowButton)
                    .addComponent(tallinnButton)
                    .addComponent(newYorkButton)
                    .addComponent(utcButton))
                .addContainerGap(290, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(systemTimeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bangkokButton, delhiButton, losAngelesButton, moscowButton, newYorkButton, tallinnButton, utcButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minutesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(setTimeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(systemTimeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(localTimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(timeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(utcButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newYorkButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tallinnButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(losAngelesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bangkokButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moscowButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delhiButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTimeButtonActionPerformed
        uTime = new UniversalTime(Integer.valueOf(hoursTextField.getText()),
                                  Integer.valueOf(minutesTextField.getText()),
                                  1);
        localTimeLabel.setText(uTime.toString());
    }//GEN-LAST:event_setTimeButtonActionPerformed

    private void systemTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemTimeButtonActionPerformed
        // TODO add your handling code here:
        uTime = new UniversalTime(1);
        localTimeLabel.setText(uTime.toString());
    }//GEN-LAST:event_systemTimeButtonActionPerformed

    private void utcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utcButtonActionPerformed
        timeLabel.setText(uTime.getUtcTime());
    }//GEN-LAST:event_utcButtonActionPerformed

    private void newYorkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newYorkButtonActionPerformed
         timeLabel.setText(uTime.getNewYorkTime());
    }//GEN-LAST:event_newYorkButtonActionPerformed

    private void tallinnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tallinnButtonActionPerformed
         timeLabel.setText(uTime.getTallinnTime());
    }//GEN-LAST:event_tallinnButtonActionPerformed

    private void losAngelesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_losAngelesButtonActionPerformed
         timeLabel.setText(uTime.getLosAngelesTime());
    }//GEN-LAST:event_losAngelesButtonActionPerformed

    private void bangkokButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkokButtonActionPerformed
         timeLabel.setText(uTime.getBangkokTime());
    }//GEN-LAST:event_bangkokButtonActionPerformed

    private void moscowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moscowButtonActionPerformed
         timeLabel.setText(uTime.getMoscowTime());
    }//GEN-LAST:event_moscowButtonActionPerformed

    private void delhiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delhiButtonActionPerformed
         timeLabel.setText(uTime.getDelhiTime());
    }//GEN-LAST:event_delhiButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bangkokButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton delhiButton;
    private javax.swing.JTextField hoursTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel localTimeLabel;
    private javax.swing.JButton losAngelesButton;
    private javax.swing.JTextField minutesTextField;
    private javax.swing.JButton moscowButton;
    private javax.swing.JButton newYorkButton;
    private javax.swing.JButton setTimeButton;
    private javax.swing.JButton systemTimeButton;
    private javax.swing.JButton tallinnButton;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JButton utcButton;
    // End of variables declaration//GEN-END:variables

}