/*
 * MainFrame.java
 *
 * Created on Dec 30, 2011, 11:41:24 AM
 * @author fred
 */
public class MainFrame extends javax.swing.JFrame {

    
    
    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        evenLabel = new javax.swing.JLabel();
        primeLabel = new javax.swing.JLabel();
        perfectLabel = new javax.swing.JLabel();
        abundantLabel = new javax.swing.JLabel();
        deficientLabel = new javax.swing.JLabel();
        palindromeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analyse Integer Number");

        inputTextField.setText("0");
        inputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Number :");

        evenLabel.setText("-");

        primeLabel.setText("-");

        perfectLabel.setText("-");

        abundantLabel.setText("-");

        deficientLabel.setText("-");

        palindromeLabel.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(abundantLabel)
                            .addComponent(primeLabel)
                            .addComponent(evenLabel)
                            .addComponent(deficientLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(inputTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(palindromeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(perfectLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(evenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(primeLabel)
                .addGap(20, 20, 20)
                .addComponent(perfectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abundantLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deficientLabel)
                .addGap(18, 18, 18)
                .addComponent(palindromeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTextFieldActionPerformed
        IntegerNumber in = new IntegerNumber(Integer.valueOf(inputTextField.getText()));
        if (in.isEven())       evenLabel.setText      ("This number is even.");
        else                   evenLabel.setText      ("This number is not even.");

        if (in.isPrime())      primeLabel.setText     ("This number is prime.");
        else                   primeLabel.setText     ("This number is not prime.");
 
        if (in.isPerfect())    perfectLabel.setText   ("This number is perfect.");
        else                   perfectLabel.setText   ("This number is not perfect.");
 
        if (in.isAbundant())   abundantLabel.setText  ("This number is abundant.");
        else                   abundantLabel.setText  ("This number is not abundant.");

        if (in.isDeficient())  deficientLabel.setText ("This number is deficient.");
        else                   deficientLabel.setText ("This number is not deficient.");
 
        if (in.isPalindrome()) palindromeLabel.setText("This number is a palindrome.");
        else                   palindromeLabel.setText("This number is not a palindrome.");
        
        //Amélioration ergonomie: pas besoin d'effacer l'ancien nombre entré
        inputTextField.selectAll();
        inputTextField.requestFocus();
    }//GEN-LAST:event_inputTextFieldActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abundantLabel;
    private javax.swing.JLabel deficientLabel;
    private javax.swing.JLabel evenLabel;
    private javax.swing.JTextField inputTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel palindromeLabel;
    private javax.swing.JLabel perfectLabel;
    private javax.swing.JLabel primeLabel;
    // End of variables declaration//GEN-END:variables

}