import java.awt.Color;
import java.awt.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Leyph
 */
public class DrawPanel extends javax.swing.JPanel {
    
    private int x = 20;
    private int y = 20;
    private int velocityX = 1;
    private int velocityY = 1;
    private int size = 40;
    
    public void move(){
        x += velocityX;
        y += velocityY;
    }
    
    public void setSize(int size) {
        this.size = size;
    }
    
    /**
     * Creates new form DrawPanel
     */
    public DrawPanel() {
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g) {
        int w = getWidth();
        int h = getHeight();
        
        move();
        
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, w, h);
        
        if (x <= size/2){
            velocityX *= -1;
        }else if (x >= w-size/2){
            velocityX *= -1;
        }
        
        if (y >= h-size/2){
            velocityY *= -1;
        }else if (y <= size/2){
            velocityY *= -1;
        }
        
        g.setColor(Color.RED);
        g.fillOval(x-size/2, y-size/2, size, size);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
